### ISSUE TITLE
"pure" ESMACS/WF3 workflow workflow

### ISSUE THREAD

**Issue by shantenujha** [IMPECCABLE-GB20/integration-level-0#3]
Need tested "pure" WF3 script on Summit to enable integration.

**Comment by apbhati1** [comment]
I think the code I provided to @darkwhite29 should be able to achieve this. @darkwhite29 please confirm and close this issue if you are satisfied. Thanks

**Comment by darkwhite29** [comment]
The code is capable of doing so. I am not able to close this issue due to permission I guess. @shantenujha Please help. Thanks!

**Comment by shantenujha** [comment]
@darkwhite29 I don't see why you can't close it. I see you with permissions that others have, "member" . Also, it should be the case that some one assigned the ticket can both comment and close the ticket. I don't think closing a ticket is restricted to the person opening the ticket. Would you agree?

**Comment by darkwhite29** [comment]
@shantenujha I cannot see the "Close" button on this page -- there is only a "Comment" button for me. @apbhati1 Are you able to see the "Close" button and close the issue? Thanks!

**Comment by apbhati1** [comment]
Actually, even I do not seem to be allowed to close the issue. Usually, there is a "comment and close" option but I can't see that here.

**Comment by shantenujha** [comment]
Bizarre. I see the "close with comment" button. For some reason, it appears that only the person who opened can close ... I"m closing for now, but it would be good to confirm if this is indeed the case ...
